version: "3.8"
services:
    nodeserver:
        build:
            context: ./backend
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./backend/nginx
        ports:
            - 8000:80
            - 5000:443
    reactserver:
        build:
            context: ./frontend
        ports:
            - 3001:80
            - 3000:443
