name: "Frontend CI"

on:
  push:
    branches:
      - "*"

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run linter
        working-directory: ./frontend/
        run: npm run lint
