name: "Frontend CI"

on:
  push:
    branches:
      - "*"

jobs:
  codestyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - uses: actions/checkout@v2

      - name: Node js setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
