name: "Frontend CI"

on:
  push:
    branches:
      - "*"

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: move to front-end directory
      - run: cd frontend/

      - name: Run linter
      - run: npm run lint
